id: ID46D1A3E
legacy_id: P007049
ocr_import_info:
  bdrc_scan_id: W19222
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T06:05:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:14:49.380390+00:00'
last_modified: 2022-08-30 23:16:32.976421
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19222
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW19222
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྭ་ལུང་དཀར་བརྒྱུད་གསེར་འཕྲེང་།
statistics:
  ocr_word_mean_confidence_index: 0.6313208621954434
  ocr_word_median_confidence_index: 0.6499999761581421
quality: null
bases:
  I3194:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3194
      total_pages: 460
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3194.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6446265765560426
    legacy_id: v001
  I3197:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3197
      total_pages: 482
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3197.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.6081148122672378
    legacy_id: v004
  I3195:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3195
      total_pages: 454
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3195.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6388174792574864
    legacy_id: v002
  I3196:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3196
      total_pages: 502
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3196.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6296995972161086
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
