id: ID46D1A3E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:09:13+00:00'
last_modified: '2022-06-08T16:18:00.637081+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19222
  title: རྭ་ལུང་དཀར་བརྒྱུད་གསེར་འཕྲེང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D198:
      image_group_id: I3194
      title: ''
      total_pages: 460
      order: 1
      base_file: D198.txt
    2AF0:
      image_group_id: I3195
      title: ''
      total_pages: 454
      order: 2
      base_file: 2AF0.txt
    79A2:
      image_group_id: I3196
      title: ''
      total_pages: 502
      order: 3
      base_file: 79A2.txt
    '5937':
      image_group_id: I3197
      title: ''
      total_pages: 482
      order: 4
      base_file: 5937.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
